release/display/urls.py
from django.conf.urls import url
from . import views

app_name = 'display'
urlpatterns=[
    url(r'^$', views.index, name="index"),
    url(r'^today/recommendation', views.recommendation, name="recommendation"),
    url(r'^(?P<category>[\u4e00-\u9fa5]+)/$', views.category, name='category'),
    url(r'^search/', views.search, name='search'),
    # url(r'^today/interest', views.interest, name="interest"),
    # url(r'^today/hit', views.hit, name="interest"),

    url(r'^personal_info/', views.personal_info, name='personal_info'),
    url(r'^personal_interest/', views.personal_interest, name='personal_interest'),
    url(r'^personal_warehouse/', views.personal_warehouse, name='personal_warehouse'),
    url(r'^personal_interest/', views.personal_interest, name='personal_interest'),
    url(r'^modify_interest/', views.modify_interest, name='modify_interest'),
    url(r'^modify_keywords/', views.modify_keywords, name='modify_keywords'),
    url(r'^add_collection/', views.add_collection, name='add_collection'),
    url(r'^(?P<url>[\s\S]*)', views.click, name='click'),

]

release/release/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('display.urls')),
    url(r'^index/', include('user_system.urls')),

]

release/user_system/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'login'
urlpatterns = [
        url(r'^$', views.login, name='login'),
        url(r'^register/$', views.register, name='register'),
        url(r'^logout/$', views.logout, name='logout'),
        url(r'^user_confirm/$', views.user_confirm,),
        # url(r'^personal_info/$', views.personal_info, name="personal_info"),
        # url(r'^update_info/$', views.update_info, name="update_info"),
        url(r'^send_code/$', views.send_code, name="send_code"),
        url(r'^forget_code/$', views.forget_password, name='forget_password'),
        url(r'^add_label/', views.add_label, name='add_label'),
        url(r'^delete_label/(?P<label>[\s\S]*)/$', views.delete_label, name='delete_label'),
]

release/user_system/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(unique=True, max_length=20)
    age = models.CharField(max_length=10, default="老大叔")
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=256, default="123456")
    has_confirmed = models.BooleanField(default=False)
    # c_time = models.DateTimeField(auto_now_add=True)

    fans_count = models.IntegerField(default=0)
    read_count = models.IntegerField(default=0)
    labels = models.CharField(max_length=100, default=None, null=True)

    collect_count = models.IntegerField(default=0)
    code = models.IntegerField(default=000000)

    def __str__(self):
        return self.name


class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User')
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name + ":   " + self.code

    class Meta:

        ordering = ["-c_time"]
        verbose_name = "确认码"
        verbose_name_plural = "确认码"


class Fan(models.Model):
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
        # 这个参数我们可以不设置，Django会默认以模型的小写作为反向关联名
        related_name='all_fans',
    )

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Interest(models.Model):
    user = models.OneToOneField(User)
    first_interest = models.CharField(default=None, max_length=20, null=True)
    second_interest = models.CharField(default=None, max_length=20, null=True)
    third_interest = models.CharField(default=None, max_length=20, null=True)
    key_words = models.CharField(default=None, max_length=10, null=True)

    def __str__(self):
        return self.first_interest


class History(models.Model):
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
    )
    title_link = models.URLField(default='www.baidu.com')
    item_title = models.CharField(default='news', max_length=50)

    def __str__(self):
        return self.item_title


class Collection(models.Model):
    label = models.ForeignKey(
        'Label',
        on_delete=models.CASCADE,
    )
    title_link = models.URLField(default='www.baidu.com')
    item_title = models.CharField(default='news', max_length=50, unique=True)

    def __str__(self):
        return self.item_title


class Label (models.Model):
    user = models.ForeignKey(
        'User',
        on_delete=models.CASCADE,
    )
    label = models.CharField(default='最喜欢', max_length=10, unique=True)

release/user_system/views.py
from django.shortcuts import render, redirect
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from .models import User, ConfirmString, Interest, Label
from django.conf import settings

import datetime
import hashlib
import random


# Create your views here.

def login(request):
    if request.session.get('is_login', None):
        return redirect('/main/')
    if request.POST:
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            name = email.strip()
            user = User.objects.get(email=name)
        except(KeyError, User.DoesNotExist):
            return render(request, 'user_system/login.html', {'error_info': 'email is incorrect'})

        if hash_code(password) == user.password:

            if not user.has_confirmed:
                return render(request, 'user_system/login.html', {'error_info': 'The email has not been validated yet '})

            request.session['is_login'] = True
            request.session['user_id'] = user.id
            request.session['user_name'] = user.name
            request.session['email_address'] = user.email
            request.session['age'] = user.age
            request.session['labels'] = user.labels.split('/')[1:]

            request.session['fan'] = user.fans_count
            request.session['collect'] = user.collect_count

            # more info about redirect in 'https://docs.djangoproject.com/en/2.0/topics/http/shortcuts/'
            return redirect('/main/')
        else:
            return render(request, 'user_system/login.html', {'error_info': 'password is incorrect'})

    return render(request, 'user_system/login.html')


def hash_code(s, salt='centos'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


# form a hash code as the key
def make_confirm_string(user):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.name, now)
    ConfirmString.objects.create(code=code, user=user,)
    return code


def register(request):
    if request.session.get('is_login', None):
        return redirect('/main/')

    if request.POST:
        name = request.POST.get('name')
        password = request.POST.get('password')
        age = request.POST.get('age')
        # 保证邮箱是有效的
        try:
            email = request.POST.get('email')
            validate_email(email)
        except ValidationError:
            return render(request, 'user_system/login.html', {'error_info': 'Email is not valid '})

        # 确保email是unique
        anonymous = User.objects.filter(email=email)
        if anonymous:
            return render(request, 'user_system/login.html', {'error_info': 'The email you filled in is registered already'})

        # 确保name是unique
        anonymous = User.objects.filter(name=name)
        if anonymous:
            return render(request, 'user_system/login.html', {'error_info': 'The name you filled in is registered already'})

        # 创建一个新用户
        user = User(name=name, email=email, age=age, password=hash_code(password))
        user.save()
        interest = Interest(user=user)
        interest.save()
        label = Label(user=user, label='最喜欢')
        label.save()
        code = make_confirm_string(user)
        send_email(email, code)
        return render(request, 'user_system/login.html', {'error_info': '请前往注册邮箱，进行邮件确认！'})

    return render(request, 'user_system/login.html', {'error_info': 'failed'})


def send_code(request):
    code = ""
    for i in range(0, 6):
        digit = int(random.random() * 10)
        code += str(digit)

    message = "Failed"
    if request.POST:
        try:
            code_email = request.POST.get('email')
            validate_email(code_email)
        except ValidationError:
            return render(request, 'user_system/login.html', {'error_info': 'Email is not valid '})

        from django.core.mail import EmailMultiAlternatives
        subject = '来自的今日发布的密码修改提示！'
        text_content = '你的验证码是 ' + code + '!'
        msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [code_email])
        msg.send()
        message = "邮件已发送 "

        # 对比  save（）和 update（）：https://blog.csdn.net/luojie140/article/details/78052408
        User.objects.filter(email=code_email).update(code=code)

        return render(request, 'user_system/login.html', {'error_info': message, 'user_email': code_email})

    return render(request, 'user_system/login.html', {'error_info': message})


def send_email(email, code):

    from django.core.mail import EmailMultiAlternatives

    subject = '欢迎访问今日发布！'

    text_content = '来自 今日发布 的测试邮件, 欢迎访问！'

    html_content = '''
                    欢迎来到 <a href="http://{}/index/user_confirm/?code={}" target=blank>今日发布</a>，
                    来自今日发布的测试邮件, 欢迎访问！</p>
                    <p>请点击站点链接完成注册确认！</p>
                    <p>此链接有效期为 {} 天！</p>
                    '''.format('127.0.0.1:8000', code, settings.CONFIRM_DAYS)

    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


def forget_password(request):
    error_info = "Failed"
    if request.POST:
        code_email = request.POST.get('user_email')
        check_code = request.POST.get('code')
        if not check_code:
            error_info = "你的验证码没有输入哦"

        else:
            user = User.objects.get(email=code_email)
            code = user.code
            if code == int(check_code):
                password = request.POST.get('password')
                if len(password) < 6:
                    error_info = "密码太短啦，长一点好不洛"

                else:
                    user = User.objects.get(email=code_email)
                    user.password = hash_code(password)
                    user.save()
                    error_info = '密码重置完成！'
            else:
                error_info = '验证码不对呢'
    return render(request, 'user_system/login.html', {'error_info': error_info})


def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = ConfirmString.objects.get(code=code)
    except:
        message = '无效的确认请求!'
        return render(request, 'user_system/confirm.html', locals())

    c_time = confirm.c_time

    # datetime.datetime.now is not timezone aware. more info: http://blog.csdn.net/qq_25420115/article/details/53149669
    from django.utils import timezone
    now = timezone.now()
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的邮件已经过期！请重新注册!'
        return render(request, 'user_system/confirm.html', locals())
    else:
        confirm.user.has_confirmed = True
        confirm.user.save()
        confirm.delete()
        message = '感谢确认，请使用账户登录！'
        return render(request, 'user_system/confirm.html', locals())


def logout(request):
    if request.session.get('is_login', None):
        request.session.flush()

    return redirect("/main/")


def add_label(request):
    if request.POST:
        label = request.POST.get('label')
        user_email = request.session['email_address']
        user = User.objects.get(email=user_email)
        user.labels = user.labels + '/' + label
        user.save()
        request.session['labels'] = user.labels.split('/')[1:]
        history = user.history_set.all()[:10]

        return render(request, 'user_system/personal_info.html', {'history': history})


def delete_label(request, label):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    history = user.history_set.all()[:10]

    start = user.labels.index(label)
    end = start + len(label)
    label = user.labels[:start-1] + user.labels[end:]
    user.labels = label
    user.save()
    request.session['labels'] = label.split('/')[1:]

    return render(request, 'user_system/personal_info.html', {'history': history})

release/user_system/templates/user_system/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <title>{% block title %}base{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../../static/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="../../../static/jQuery/3.3.1/jquery.min.js"></script>
    <script src="../../../static/js/1.12.9_umd/popper.min.js"></script>
    <script src="../../../static/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <style>
       .user-pic{
           border-radius: 50%;
           border:solid 2px #fff;
           background: #ffde00;
           overflow: hidden;
           width:60px;
           height:60px;
           float: left;
       }

       .user-name{
           min-width: 100px;
           color: #fff;
           padding-left: 22px;
           white-space: nowrap;
           overflow: hidden;
           text-overflow: ellipsis;
           /* margin-top: 10px;*/
       }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" >
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'display:index' %}">今日发布</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '新闻' %}">新闻</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '娱乐' %}">娱乐</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '体育' %}">体育</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '音乐' %}">音乐</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '汽车' %}">汽车</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '程序员' %}">IT</a>
    </li>
  </ul>

  <form class="form-inline" action="{% url 'display:search' %}" method="post">
      {% csrf_token %}
      <input class="form-control" type="text" placeholder="Search" name="keywords">
      <button class="btn btn-success" type="submit">搜索全站</button>
  </form>
  <ul class="navbar-nav" style="position: absolute;right:0;">
      {% if not request.session.is_login %}
          <li class= "nav-item">
         <a class="nav-link" href="{% url 'login:login' %}">登录</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{% url 'login:login' %}">注册</a>
          </li>
      {% else %}
          <li class= "nav-item">
          <a class="nav-link" href="{% url 'display:personal_interest' %}">个人空间</a>
          </li>

          <li class= "nav-item">
          <a class="nav-link" href="{% url 'login:logout' %}">退出</a>
          </li>
     {% endif %}

  </ul>
</nav>
<div id="section1" class="container-fluid" style="padding-top:70px;padding-bottom:70px">
      <div class="container">
          <div style="width: 69%;display: inline-block;">
              {% block content %}{% endblock %}
          </div>
		  <div class="another-content" style="display:inline-block;width:30%;height:200px;padding:0 20px ;vertical-align: top;" >
			  <div style="width:100%; background: white;margin-bottom:20px; border-radius: 8px;">
                <div class="user-pic"> <a href="{% url 'display:personal_info' %}"><img class="img-responsive img-circle" src="https://ww4.sinaimg.cn/thumb180/c0679ecagw1faxmyl9s8ig208c08c4qp.jpg" alt="头像不在了"></a></div>
                <div class="user-name"><a href="{% url 'display:personal_info' %}">{{ request.session.user_name}}</a></div>
                <p >粉丝数：<span>{{request.session.fan}}</span>收藏：<span>{{request.session.collect}}</span></p>
              </div>

              <div style="width:100%; height:200px; background: white;margin-bottom:20px; margin-top:50px;">
                  <p>浏览历史：</p>
                  <ol class="d">
                    {% for record in history %}
                    <a href="record.title_link"><li>{{ record.item_title}}</li></a>
                    {% endfor %}
                  </ol>
              </div>
		  </div>
	</div>
</div>

</body>
</html>
<!--extends 模板只能在服务器运行的情况下才能测试-->

release/user_system/templates/user_system/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>今日发布</title>
</head>
<body>
<p>{{ message }}</p>
</body>
</html>

release/user_system/templates/user_system/personal_info.html
{% extends 'user_system/base.html' %}
{% block title %}个人信息{% endblock %}

{% block content %}
    <div class="container">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'display:personal_info' %}">个人信息</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href='{% url 'display:personal_warehouse' %}'>收藏</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'display:personal_interest' %}">兴趣偏好</a>
            </li>
        </ul>

     <table class="table table-bordered" style="margin: 1%">
        <thead>
        <tr>
            <th>用户名</th>
            <th>年纪</th>
            <th>Email</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ request.session.user_name }}</td>
            <td>{{ request.session.age }}</td>
            <td>{{ request.session.email_address }}</td>
        </tr>
    </table>
    {% if not request.session.labels %}
        <p>
        标签：<span style="display: inline-block;background:rgba(0,174,255,.5);padding: 0 5px;border-radius:5px;color: #fff;line-height:1.5;font-size:1rem;margin-left:5px;cursor: pointer;">未探索</span>
        <p>
    {% else %}
        <p>标签：
        {% for label in request.session.labels %}
            <a href="{% url 'login:delete_label' label %}"> <span style="display: inline-block;background:rgba(0,174,255,.5);padding: 0 5px;border-radius:5px;color: #fff;line-height:1.5;font-size:1rem;margin-left:5px;cursor: pointer;">{{ label }}</span></a>
        {% endfor %}
        </p>
    {% endif %}
     <form action="{% url 'login:add_label' %}" method="post">
         {% csrf_token %}
         <label for="form-room-description">新标签：</label>
         <input type="text" class="form-control col-lg-2" id="" name="label" value="">
         <button id="btn1" type="submit" class="btn btn-info">添加</button>
     </form>
    </div>

{% endblock %}

release/user_system/templates/user_system/personal_interest.html
{% extends 'user_system/base.html' %}
{% block title %}兴趣偏好{% endblock %}

{% block content %}
    <div class="container">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'display:personal_info' %}">个人信息</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href='{% url 'display:personal_warehouse' %}'>收藏</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'display:personal_interest' %}">兴趣偏好</a>
            </li>
        </ul>
        <div class="alert alert-info" style="margin: 1%">
            <strong>{{ title }}</strong> {{ error_info }}
        </div>

        <div class="card-columns" style="margin: 1%">
        <div class="card bg-light">
            <div class="card-body text-center">
                <p class="card-text">{{ first }}</p>
                <span class="badge badge-primary">一等最爱</span>
            </div>
        </div>

        <div class="card bg-light">
            <div class="card-body text-center">
                <p class="card-text">{{ second }}</p>
                <span class="badge badge-warning">次等最爱</span>
            </div>
        </div>

        <div class="card bg-light">
            <div class="card-body text-center">
                <p class="card-text">{{ third }}</p>
                <span class="badge badge-secondary">末等最爱</span>
            </div>
        </div>
        </div>

    <form class="form-inline" action="{% url 'display:modify_interest' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputName2">一等公民：</label>
            <input type="text" class="form-control col-lg-4" id="1" placeholder="修改最爱" name="first">
        </div>
        <div class="form-group">
            <label for="exampleInputName2">二等公民：</label>
            <input type="text" class="form-control col-lg-4" id="2" placeholder="修改次爱" name="second">
        </div>
        <div class="form-group">
            <label for="exampleInputName2">三等公民：</label>
            <input type="text" class="form-control col-lg-4" id="3" placeholder="修改末爱" name="third">
        </div>
        <button type="submit" class="btn btn-primary">修改</button>

    </form>

        <div>
            <div class="card-columns" style="margin: 1%">
                <div class="card bg-light">
                    <div class="card-body text-center">
                        <p class="card-text">{{ keywords }}</p>
                        <span class="badge badge-primary">关键字</span>
                    </div>
                </div>
            </div>
            <form action="{% url 'display:modify_keywords' %}" class="form-inline" method="post">
                {% csrf_token %}
                <div class="form-group" style="margin: 1%">
                    <label for="exampleInputName2">关键字：</label>
                    <input type="text" class="form-control col-lg-4" id="1" placeholder="修改关键字" name="keywords">
                    <button type="submit" class="btn btn-primary">修改</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

release/user_system/templates/user_system/personal_warehouse.html
{% extends 'user_system/base.html' %}
{% block title %}个人收藏{% endblock %}
{% load filter %}

{% block content %}
    <div class="container">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'display:personal_info' %}">个人信息</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href='{% url 'display:personal_warehouse' %}'>收藏</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'display:personal_interest' %}">兴趣偏好</a>
            </li>
        </ul>

        <div class="card-columns" style="margin: 1%">
            {% for label in labels %}
            <div class="card bg-light">
                <p><strong>{{ label }}</strong></p>
                <div class="card-body text-center">
                    {% for record in collections|dic_value:label %}
                    <a href = '{{ record.title_link }}'><p class="card-text">{{ record.item_title }}</p></a>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}