release/display/urls.py
from django.conf.urls import url
from . import views

app_name = 'display'
urlpatterns=[
    url(r'^$', views.index, name="index"),
    url(r'^today/recommendation', views.recommendation, name="recommendation"),
    url(r'^(?P<category>[\u4e00-\u9fa5]+)/$', views.category, name='category'),
    url(r'^search/', views.search, name='search'),
    # url(r'^today/interest', views.interest, name="interest"),
    # url(r'^today/hit', views.hit, name="interest"),

    url(r'^personal_info/', views.personal_info, name='personal_info'),
    url(r'^personal_interest/', views.personal_interest, name='personal_interest'),
    url(r'^personal_warehouse/', views.personal_warehouse, name='personal_warehouse'),
    url(r'^personal_interest/', views.personal_interest, name='personal_interest'),
    url(r'^modify_interest/', views.modify_interest, name='modify_interest'),
    url(r'^modify_keywords/', views.modify_keywords, name='modify_keywords'),
    url(r'^add_collection/', views.add_collection, name='add_collection'),
    url(r'^(?P<url>[\s\S]*)', views.click, name='click'),

]

release/homepage/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.index, name="index"),
    url(r'^today/recommendation', views.recommendation, name="recommendation"),
    url(r'^today/interest', views.interest, name="interest"),
    url(r'^today/hit', views.hit, name="interest"),

]

release/release/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('display.urls')),
    url(r'^index/', include('user_system.urls')),

]

release/user_system/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'login'
urlpatterns = [
        url(r'^$', views.login, name='login'),
        url(r'^register/$', views.register, name='register'),
        url(r'^logout/$', views.logout, name='logout'),
        url(r'^user_confirm/$', views.user_confirm,),
        # url(r'^personal_info/$', views.personal_info, name="personal_info"),
        # url(r'^update_info/$', views.update_info, name="update_info"),
        url(r'^send_code/$', views.send_code, name="send_code"),
        url(r'^forget_code/$', views.forget_password, name='forget_password'),
        url(r'^add_label/', views.add_label, name='add_label'),
        url(r'^delete_label/(?P<label>[\s\S]*)/$', views.delete_label, name='delete_label'),
]

release/display/models.py
from django.db import models
from time import timezone
import datetime

# python manage.py makemigrations ---record
# python manage.py migrate  --- work on database
# Create your models here.


class Item(models.Model):
    item_id = models.CharField(max_length=200, unique=True)
    item_title = models.CharField(max_length=50, default='news')
    item_type = models.CharField(max_length=10, default='最新')
    title_link = models.URLField()
    cut_url = models.URLField()
    collect_time = models.DateField()
    author = models.CharField(max_length=20, default='unknown author')

    item_source = models.CharField(max_length=20, default='unknown source')

    category = models.CharField(max_length=20, default='unknown category')

    like_count = models.IntegerField(default=0)

    view_count = models.IntegerField(default=0)

    share_count = models.IntegerField(default=0)

    def __str__(self):
        return self.item_id

    # 判断该消息是不是新消息
    def pub_in_2_days(self):

        return timezone - self.collect_time <= datetime.timedelta(days=2)


class HitItem(models.Model):
    item_id = models.CharField(max_length=200, unique=True)
    item_title = models.CharField(max_length=50, default='news')
    item_type = models.CharField(max_length=10, default='最新')
    title_link = models.URLField()

    rank = models.IntegerField(default=0)
    collect_time = models.DateField()

    item_source = models.CharField(max_length=20, default='unknown source')

    like_count = models.IntegerField(default=0)

    view_count = models.IntegerField(default=0)

    share_count = models.IntegerField(default=0)

    def __str__(self):
        return self.item_id


class Images(models.Model):
    item_id = models.IntegerField(default=0)
    item_title = models.CharField(max_length=20, default='图片')
    item_url = models.URLField(default='http://img.ivsky.com/img/bizhi/li/201602/04/nba-001.jpg')
    collect_time = models.DateField()
    item_source = models.CharField(max_length=10, default=20)
    like_count = models.IntegerField(default=0)
    category = models.CharField(max_length=10,default='你猜')

release/display/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Item
from user_system.models import User, History, Interest, Collection, Label
from display.models import Item, Images
from django.http import JsonResponse
import json
# python manage.py startapp name


# Create your views here.

def index(request, **kwargs):
    news = Item.objects.order_by("collect_time")
    daily_news = Item.objects.order_by("collect_time")[:6]
    pictures_all = Images.objects.order_by("collect_time")[:30]
    # forloop展示图片
    pictures = pictures_all[:6]
    daily_news = zip(daily_news, pictures)
    daily_news_list = Item.objects.order_by("collect_time")[6:16]
    # 配图展示
    recommended_news = []
    # 仅标题展示
    recommended_news_list = []
    # 过滤已收藏标题
    collection_list = []

    keywords_news = []
    keywords_news_list = []

    if request.session.get('is_login', None):
        user_id = request.session['user_id']
        user = User.objects.get(pk=user_id)

        for item in user.label_set.all():
            for info in item.collection_set.all():
                collection_list.append(info.item_title)

        interest = user.interest
        if interest.first_interest:
            first_interest = interest.first_interest
            news_group = news.order_by('collect_time').filter(category=first_interest)[:15]
            recommended_news_first = news_group[:5]
            recommended_news.extend(recommended_news_first)

            recommended_news_list_first = news_group[5:11]
            recommended_news_list.extend(recommended_news_list_first)

        if interest.second_interest:
            second_interest = interest.second_interest
            news_group = news.order_by('collect_time').filter(category=second_interest)[:7]
            recommended_news_second = news_group[:3]
            recommended_news.extend(recommended_news_second)

            recommended_news_list_second = news_group[3:]
            recommended_news_list.extend(recommended_news_list_second)

        if interest.third_interest:
            third_interest = interest.third_interest
            news_group = news.order_by('collect_time').filter(category=third_interest)[:4]
            recommended_news_third = news_group[:2]
            recommended_news.extend(recommended_news_third)

            recommended_news_list_third = news_group[2:]
            recommended_news_list.extend(recommended_news_list_third)

        pictures = pictures_all[6:12]
        recommended_news = zip(recommended_news, pictures)

        keywords = interest.key_words
        keywords_news_20 = news.order_by('collect_time').filter(item_title__contains=keywords)[:20]
        keywords_news = keywords_news_20[:6]

        pictures = pictures_all[12:18]
        keywords_news = zip(keywords_news, pictures)
        keywords_news_list = keywords_news_20[6:16]

    #
    pictures = pictures_all[18:24]
    hit_news = news.order_by('collect_time')[:6]
    hit_news_list = news.order_by('collect_time')[6:16]

    context = {'daily_news': daily_news,
               'pictures': pictures,
               'daily_news_list': daily_news_list,
               'recommended_news': recommended_news,
               'recommended_news_list': recommended_news_list,
               'hit_news': hit_news,
               'hit_news_list': hit_news_list,
               'collection_list': collection_list,
               'keywords_news': keywords_news,
               'keywords_news_list': keywords_news_list,
               'info': kwargs.get('info', '初次见面，请多关注！')
               }

    return render(request, 'display/homepage.html', context)


def recommendation():
    pass


    # 分类模块
def category(request, category):
    news = Item.objects.order_by("collect_time")
    news = news.order_by('collect_time').filter(category=category)[:20]
    length = str(len(news))
    pictures = Images.objects.order_by("collect_time")[:20]
    daily_news = zip(news, pictures)

    context = {
        'daily_news': daily_news,
        'info': '一共有' + length + '条记录！',
        }

    return render(request, 'display/category.html', context)


def search(request):
    if request.POST:
        keywords = request.POST.get('keywords')
        result = Item.objects.filter(item_title__contains=keywords)
        length = str(len(result))

        result = Item.objects.filter(item_title__contains=keywords)[:20]
        pictures = Images.objects.order_by('collect_time')[:20]
        result = zip(result, pictures)

        context = {
            'daily_news': result,
            'info': '一共有' + length + '条记录！',
        }

        return render(request, 'display/category.html', context)


def personal_info(request):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    history = user.history_set.all()[:10]

    return render(request, 'user_system/personal_info.html', {'history': history})


def personal_interest(request, **kw):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    history = user.history_set.all()[:10]

    interest = user.interest
    if interest.first_interest:
        first = interest.first_interest
    else:
        first = '什么都没有留下'

    if interest.second_interest:
        second = interest.second_interest
    else:
        second = '什么都没有'

    if interest.third_interest:
        third = interest.third_interest
    else:
        third = '一片空白'

    if interest.key_words:
        keywords = interest.key_words
    else:
        keywords = '什么都没有留下'

    error_info = kw.get('error_info', '我们会根据你的喜好顺序给小伙伴们推荐消息，同时支持关键字推荐哦.')
    title = kw.get('title', '听我说哈')

    context = {
        'history': history,
        'first': first,
        'second': second,
        'third': third,
        'keywords': keywords,
        'error_info': error_info,
        'title': title,
    }
    return render(request, 'user_system/personal_interest.html', context)


def personal_warehouse(request):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    history = user.history_set.all()[:10]
    labels_list = user.label_set.all()
    labels = []
    for item in labels_list:
        labels.append(item.label)

    collections = {}
    for item in labels_list:
        collection = []
        for record in item.collection_set.all():
            collection.append(record)
        collections[item.label] = collection

    context = {
        'history': history,
        'collections': collections,
        'labels': labels,
    }

    return render(request, 'user_system/personal_warehouse.html', context)


# 监听每次点击
def click(request, url):
    item = Item.objects.get(title_link=url)
    item.view_count += 1
    item.save()
    if request.session.get('is_login', None):
        user_id = request.session['user_id']
        user = User.objects.get(pk=user_id)
        record = History(user=user, title_link=url, item_title=item.item_title)
        record.save()
    return redirect(url)

def modify_interest(request):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    interest = user.interest
    if request.method == 'POST':
        title = '提示你哦：'

        first = request.POST.get('first')
        second = request.POST.get('second')
        third = request.POST.get('third')
        changed = False
        if len(first) < 5 and len(second) < 5 and len(third) < 5:
            if third:
                interest.third_interest = third
                changed = True
            if first:
                interest.first_interest = first
                changed = True
            if second:
                interest.second_interest = second
                changed = True
            if changed:
                interest.save()
                error_info = '保存成功。'
        else:
            error_info = '输入内容太长了，别超过5个字符哦。'

    # 重定向
    return personal_interest(request, title=title, error_info=error_info)


def modify_keywords(request):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    interest = user.interest

    if request.method == 'POST':
        key_words = request.POST.get('keywords')
        title = '提示你哦：'
        if key_words and len(key_words) < 10:
            interest.key_words = key_words
            interest.save()
            error_info = '修改成功啦'
        else:
            error_info = "我猜，你要么没有输入，要么就是输入内容太长了（小于10个字符）"

    # 重定向
    return personal_interest(request, title=title, error_info=error_info)


def add_collection(request):
    user_id = request.session['user_id']
    user = User.objects.get(pk=user_id)
    label = user.label_set
    if request.method == "POST":
        data = json.loads(request.body)
        topic = data['type']
        name = data['name']
        url = data['url']
        if topic and name and url:
            label_name = label.filter(label=topic)
            if label_name:
                record = Collection(label=label_name[0], item_title=name, title_link=url)
            else:
                label = Label(user=user, label=topic)
                label.save()
                record = Collection(label=label, item_title=name, title_link=url)

            record.save()
            user.collect_count += 1
            user.save()
            request.session['collect'] = user.collect_count
        else:
            return JsonResponse({'info': '保存失败!'})

    return JsonResponse({'info': '保存成功！'})

release/display/templates/display/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>今日发布</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../../static/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="../../../static/jQuery/3.3.1/jquery.min.js"></script>
    <script src="../../../static/js/1.12.9_umd/popper.min.js"></script>
    <script src="../../../static/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <script>
    function collection(url, name, type, click_id){
        console.log(url, name, type);
        var submit_data= {
            url: url,
            name: name,
            type: type
        };

        $.ajax({
                url:"{% url 'display:add_collection' %}",
{#                启用原生模式传输#}
                tradition:true,
{#              通过JSON.stringify()方法将数组以json格式转换成字符串#}
                data:JSON.stringify(submit_data),
                type:'POST',
{#                success用来接收login()函数执行之后的return HttpResponse返回值#}
                success:function(arg){
{#                    因为接收到的是json object,所以需要调用JSON.stringify字符串化，然后解析#}
                    arg = JSON.stringify(arg);
                    var info_list= $.parseJSON(arg);
                    var alert_str=info_list.info;
                    $('#info').text(alert_str);
                    $('#'+click_id).remove();

                }
            });
    }
    </script>
    <style>
       .user-pic{
           border-radius: 50%;
           border:solid 2px #fff;
           background: #ffde00;
           overflow: hidden;
           width:60px;
           height:60px;
           float: left;
       }

       .user-name{
           min-width: 100px;
           color: #fff;
           padding-left: 22px;
           white-space: nowrap;
           overflow: hidden;
           text-overflow: ellipsis;
           /* margin-top: 10px;*/
       }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" >
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'display:index' %}">今日发布</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '新闻' %}">新闻</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '娱乐' %}">娱乐</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '体育' %}">体育</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '音乐' %}">音乐</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '汽车' %}">汽车</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display:category' '程序员' %}">IT</a>
    </li>
  </ul>

  <form class="form-inline" action="{% url 'display:search' %}" method="post">
      {% csrf_token %}
      <input class="form-control" type="text" placeholder="Search" name="keywords">
      <button class="btn btn-success" type="submit">搜索全站</button>
  </form>

  <ul class="navbar-nav" style="position: absolute;right:0;">
      {% if not request.session.is_login %}
          <li class= "nav-item">
         <a class="nav-link" href="{% url 'login:login' %}">登录</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{% url 'login:login' %}">注册</a>
          </li>
      {% else %}
          <li class= "nav-item">
          <a class="nav-link" href="{% url 'display:personal_interest' %}">个人空间</a>
          </li>

          <li class= "nav-item">
          <a class="nav-link" href="{% url 'login:logout' %}">退出</a>
          </li>
     {% endif %}

  </ul>
</nav>

<div id="section1" class="container-fluid" style="padding-top:70px;padding-bottom:70px">
      <div class="container">
          <div class="alert alert-info" style="margin: 1%">
            <strong id="info">{{ info }}</strong>
          </div>
          <div class="list-group" style="width: 69%;display: inline-block;">
              <h2 style="display:block;line-height:76px;">搜索结果</h2>
              {% if daily_news %}
                  {% for news, picture in daily_news %}
                      <div class="list-group-item list-group-item-action" style="margin-bottom:20px; overflow: hidden;">
                          <img src="{{ picture.item_url }}" class="float-right" alt="Cinque Terre" width="100">
                          <div>
                              <div>
                                  <a href="{% url 'display:click' news.title_link %}" target="_blank" id = "link_{{ forloop.counter0 }}">{{news.item_title}}</a><span style="display: inline-block;background:rgba(0,174,255,.5);padding: 0 5px;border-radius:5px;color: #fff;line-height:1.5;font-size:1rem;margin-left:5px;cursor: pointer;">{{ news.category }}</span>
                                  <p>浏览数:<span>{{news.view_count}}</span> 来源:<span>{{news.author}}</span> 时间:<span>{{news.collect_time}}</span></p>

                                  {% if news.item_title not in collection_list %}
                                      <button id='click_{{ forloop.counter0 }}' type="button" class="btn btn-outline-primary" onclick="collection('{{ news.title_link }}', '{{news.item_title}}', '{{ news.category }}', 'click_{{ forloop.counter0 }}')">
                                          收藏
                                      </button>
                                  {% else %}
                                      <button type="button" class="btn">
                                      收藏
                                     </button>
                                  {% endif %}

                              </div>
                          </div>
                      </div>
                  {% endfor %}
              {% endif %}

          </div>

          <div class="another-content" style="display:inline-block;width:30%;height:200px;padding:0 20px ;vertical-align: top;" >
              {% if request.session.is_login %}
              <div style="width:100%; background: white;margin-bottom:20px; border-radius: 8px;">
                <div class="user-pic"> <a href="{% url 'display:personal_info' %}"><img class="img-responsive img-circle" src="https://ww4.sinaimg.cn/thumb180/c0679ecagw1faxmyl9s8ig208c08c4qp.jpg" alt="头像不在了"></a></div>
                <div class="user-name"><a href="{% url 'display:personal_info' %}">{{ request.session.user_name}}</a></div>
                <p >粉丝数：<span>{{request.session.fan}}</span>收藏：<span>{{request.session.collect}}</span></p>
              </div>
              {% else %}
              <div style="width:100%; background: white;margin-bottom:20px; border-radius: 8px;">
                <div class="user-pic"> <a href=""><img class="img-responsive img-circle" src="../../../static/picture/userpic.png" alt="头像不在了"></a></div>
                <div class="user-name"><a href="{% url 'login:login' %}">未登陆</a></div>
              </div>
              {% endif %}

              <div style="width:100%; height:200px; background: white;margin-bottom:20px; margin-top:50px;">
                <ol class="d">
                    {% for news in daily_news_list %}
                    <a href="{{ news.title_link }}"><li>{{ news.item_title}}</li></a>
                    {% endfor %}
                </ol>
              </div>

          </div>
      </div>
</div>
</body>
</html>